trigger:
  - main
  # paths:
  #   include:
  #     - docker

pr:
  - main

resources:
  - repo: self

variables:
  # Note: to customize the pipeline to use private ACRs other than commondockerimages,
  # you need to change BOTH dockerRegistryServiceConnection and containerRegistryName

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "442ea973-c852-4792-aa09-fab4a9df791f"
  containerRegistryName: "commondockerimages.azurecr.io"

  dockerfileazuremlPath: "$(Build.SourcesDirectory)/docker/Dockerfile_base_azureml"
  dockerfileazuremlnightlyPath: "$(Build.SourcesDirectory)/docker/Dockerfile_base_azureml_nightly"
  dockerfilenvidiaPath: "$(Build.SourcesDirectory)/docker/Dockerfile_base_nvidia"

  tagLatest: "latest"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  # docs: https://docs.microsoft.com/azure/devops/pipelines/languages/docker
  - stage: BuildDockerImagesAndRunPytest
    displayName: Build docker; run pytests on built images
    jobs:
      - job: DefineDockerTags
        displayName: define docker tags
        pool:
          vmImage: $(vmImageName)
        steps:
          - bash: |
              github_organization_prefix="AutonomousSystemsResearch/"
              full_repo_name=$(Build.Repository.Name)
              repo_name=${full_repo_name#"$github_organization_prefix"}
              branch_name=$(Build.SourceBranchName)

              git_short_hash_main=`git rev-parse --short=7 HEAD`
              git_hash_pr=$(System.PullRequest.SourceCommitId)
              git_short_hash_pr=${git_hash_pr:0:7}
              pr_number=$(System.PullRequest.PullRequestNumber)

              tag_main_git_commit=main-$git_short_hash_main
              tag_pr_git_commit=PR-$pr_number-$git_short_hash_pr
              tag_pr_latest=PR-$pr_number-latest

              echo ""
              echo "full repo name:  $(Build.Repository.Name)"
              echo "repo name:  $repo_name"
              echo "Build Id:  $(Build.BuildId)"
              echo "Build BuildNumber:  $(Build.BuildNumber)"
              echo "Build Reason:  $(Build.Reason)"
              echo "Build Branch Name:  $(Build.SourceBranchName)"
              echo "git commit message: $(Build.SourceVersionMessage)"
              echo "git hash (main branch):  $(Build.SourceVersion)"
              echo "git hash short (main branch): $git_short_hash_main"
              echo "PR branch: $(System.PullRequest.SourceBranch)"
              echo "PR number: $(System.PullRequest.PullRequestNumber)"
              echo "PR ID: $(System.PullRequest.PullRequestId)"
              echo "git hash (PR branch): $(System.PullRequest.SourceCommitId)"
              echo "git hash short (PR branch): : $git_short_hash_pr"

              # set pipeline variables which can be referenced in the jobs that follow to tag docker images appropriately
              echo "##vso[task.setvariable variable=repoName;isoutput=true]$repo_name"
              echo "##vso[task.setvariable variable=tagPRLatest;isoutput=true]$tag_pr_latest"

              if [[ "$branch_name" == "main" ]]; then
                echo "##vso[task.setvariable variable=tagOfThisBuild;isoutput=true]$tag_main_git_commit"
              fi
              if [[ "$branch_name" == "merge" ]]; then
                echo "##vso[task.setvariable variable=tagOfThisBuild;isoutput=true]$tag_pr_git_commit"
              fi

              ## deprecated; but might be of use in the future
              # echo "##vso[task.setvariable variable=tagMainGitCommitHash;isoutput=true]$tag_main_git_commit"
              # echo "##vso[task.setvariable variable=tagPRGitCommitHash;isoutput=true]$tag_pr_git_commit"

              # print tags:
              echo "tag_pr_latest:  $tag_pr_latest"
              echo "tag_pr_git_commit:  $tag_pr_git_commit"
              echo "tag_main_git_commit:  $tag_main_git_commit"

              # print outputvars:
              echo "tag_pr_latest:  $tag_pr_latest"
              echo "tag_pr_git_commit:  $tag_pr_git_commit"
              echo "tag_main_git_commit:  $tag_main_git_commit"
            name: DockerTagVars # because we're going to depend on it, we need to name the step
            displayName: (debug) print git info

      - job: BuildDockerAzureMLBase
        dependsOn: DefineDockerTags
        displayName: build azureml; run pytest
        pool:
          vmImage: $(vmImageName)
        variables:
          tagOfThisBuild: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.tagOfThisBuild'] ]
          tagPRLatest: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.tagPRLatest'] ]
          repoName: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.repoName'] ]
        steps:
          - bash: |
              echo "repoName: $(repoName)"
              echo "tagOfThisBuild: $(tagOfThisBuild)"
              echo "tagPRLatest: $(tagPRLatest)"
            displayName: (debug) print pipeline vars

          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              command: buildAndPush
              repository: $(repoName)
              dockerfile: $(dockerfileazuremlPath)
              containerRegistry: $(dockerRegistryServiceConnection)
              ${{ if eq(variables['Build.SourceBranchName'], 'merge') }}:
                tags: |
                  $(tagOfThisBuild)-azureml
                  $(tagPRLatest)-azureml
                  $(tagPRLatest)
              ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
                tags: |
                  $(tagOfThisBuild)-azureml
                  $(tagLatest)-azureml
                  $(tagLatest)

          - bash: |
              docker run -d -i --name testapp -v $(Build.SourcesDirectory):/workdir -w /workdir $(containerRegistryName)/$(repoName):$(tagOfThisBuild)-azureml
              docker exec testapp bash -c "python3 -c \"import torch; print('torch: version', torch.__version__)\""
              docker exec testapp bash -c "python3 -c \"import pytorch_lightning; print('pytorch_lightning: version', pytorch_lightning.__version__)\""
              docker exec testapp bash -c "python3 -c \"import torch; print('torch.cuda.version:', torch.version.cuda)\""
            displayName: print versions

          - script: |
              docker exec testapp bash -c "pip install -e .; pytest tests/test_dev_fast_run.py -k test_fast_dev_run_cpu"
            displayName: pytest

      - job: BuildDockerAzureMLBaseNightly
        dependsOn: DefineDockerTags
        displayName: build azureml nightly; run pytest
        pool:
          vmImage: $(vmImageName)
        variables:
          tagOfThisBuild: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.tagOfThisBuild'] ]
          tagPRLatest: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.tagPRLatest'] ]
          repoName: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.repoName'] ]
        steps:
          - bash: |
              echo "repoName: $(repoName)"
              echo "tagOfThisBuild: $(tagOfThisBuild)-azureml-nightly"
              echo "tagPRLatest: $(tagPRLatest)-azureml-nightly"
            displayName: (debug) print pipeline vars

          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              command: buildAndPush
              repository: $(repoName)
              dockerfile: $(dockerfileazuremlnightlyPath)
              containerRegistry: $(dockerRegistryServiceConnection)
              ${{ if eq(variables['Build.SourceBranchName'], 'merge') }}:
                tags: |
                  $(tagOfThisBuild)-azureml-nightly
                  $(tagPRLatest)-azureml-nightly
              ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
                tags: |
                  $(tagOfThisBuild)-azureml-nightly
                  $(tagLatest)-azureml-nightly

          - bash: |
              docker run -d -i --name testapp -v $(Build.SourcesDirectory):/workdir -w /workdir $(containerRegistryName)/$(repoName):$(tagOfThisBuild)-azureml-nightly
              docker exec testapp bash -c "python3 -c \"import torch; print('torch: version', torch.__version__)\""
              docker exec testapp bash -c "python3 -c \"import pytorch_lightning; print('pytorch_lightning: version', pytorch_lightning.__version__)\""
              docker exec testapp bash -c "python3 -c \"import torch; print('torch.cuda.version:', torch.version.cuda)\""
            displayName: print versions

          - script: |
              docker exec testapp bash -c "pip install -e .; pytest tests/test_dev_fast_run.py -k test_fast_dev_run_cpu"
            displayName: pytest

      - job: BuildDockerNvidiaBasePipInstall
        dependsOn: DefineDockerTags
        displayName: build nvidia pytorch; run pytest
        pool:
          vmImage: $(vmImageName)
        variables:
          tagOfThisBuild: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.tagOfThisBuild'] ]
          tagPRLatest: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.tagPRLatest'] ]
          repoName: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.repoName'] ]
        steps:
          - bash: |
              echo "repoName: $(repoName)"
              echo "tagOfThisBuild: $(tagOfThisBuild)-nvidia"
              echo "tagPRLatest: $(tagPRLatest)-nvidia"

              # echo "tagMainGitCommitHash: $(tagMainGitCommitHash)"
              # echo "tagPRGitCommitHash: $(tagPRGitCommitHash)"
            displayName: (debug) print pipeline vars

          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              command: buildAndPush
              repository: $(repoName)
              dockerfile: $(dockerfilenvidiaPath)
              containerRegistry: $(dockerRegistryServiceConnection)
              ${{ if eq(variables['Build.SourceBranchName'], 'merge') }}:
                tags: |
                  $(tagOfThisBuild)-nvidia
                  $(tagPRLatest)-nvidia
              ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
                tags: |
                  $(tagOfThisBuild)-nvidia
                  $(tagLatest)-nvidia

          - bash: |
              docker run -d -i --name testapp -v $(Build.SourcesDirectory):/workdir -w /workdir $(containerRegistryName)/$(repoName):$(tagOfThisBuild)-nvidia
              docker exec testapp bash -c "python3 -c \"import torch; print('torch: version', torch.__version__)\""
              docker exec testapp bash -c "python3 -c \"import pytorch_lightning; print('pytorch_lightning: version', pytorch_lightning.__version__)\""
              docker exec testapp bash -c "python3 -c \"import torch; print('torch.cuda.version:', torch.version.cuda)\""
            displayName: print versions

          - script: |
              docker exec testapp bash -c "pip install -e .; pytest tests/test_dev_fast_run.py -k test_fast_dev_run_cpu"
            displayName: pytest

      - job: PytestAzureMLBaseTagLatest
        dependsOn: DefineDockerTags
        displayName: pytest latest-azureml
        pool:
          vmImage: $(vmImageName)
        variables:
          repoName: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.repoName'] ]
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - script: |
              docker run -d -i --name testapp -v $(Build.SourcesDirectory):/workdir -w /workdir $(containerRegistryName)/$(repoName):$(tagLatest)-azureml
            displayName: docker pull and run

          - script: |
              docker exec testapp bash -c "pip install -e .; pytest tests/test_dev_fast_run.py -k test_fast_dev_run_cpu"
            displayName: pytest

      - job: PytestAzureMLBaseTagLatestNightly
        dependsOn: DefineDockerTags
        displayName: pytest latest-azureml-nightly
        pool:
          vmImage: $(vmImageName)
        variables:
          repoName: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.repoName'] ]
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - script: |
              docker run -d -i --name testapp -v $(Build.SourcesDirectory):/workdir -w /workdir $(containerRegistryName)/$(repoName):$(tagLatest)-azureml-nightly
            displayName: docker pull and run

          - script: |
              docker exec testapp bash -c "pip install -e .; pytest tests/test_dev_fast_run.py -k test_fast_dev_run_cpu"
            displayName: pytest

      - job: PytestNvidiaBaseTagLatest
        dependsOn: DefineDockerTags
        displayName: pytest latest-nvidia
        pool:
          vmImage: $(vmImageName)
        variables:
          repoName: $[ dependencies.DefineDockerTags.outputs['DockerTagVars.repoName'] ]
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - script: |
              docker run -d -i --name testapp -v $(Build.SourcesDirectory):/workdir -w /workdir $(containerRegistryName)/$(repoName):$(tagLatest)-nvidia
            displayName: docker pull and run

          - script: |
              docker exec testapp bash -c "pip install -e .; pytest tests/test_dev_fast_run.py -k test_fast_dev_run_cpu"
            displayName: pytest
