# see latest azureml base images tags here
# - https://github.com/Azure/AzureML-Containers/tree/master/base/gpu
# - https://hub.docker.com/_/microsoft-azureml?tab=description

ARG BASE_IMAGE=openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04:latest

FROM mcr.microsoft.com/azureml/${BASE_IMAGE}

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
    build-essential \
    software-properties-common \
    cmake \
    g++-7 \
    git \
    gpg \
    curl \
    vim \
    wget \
    ca-certificates \
    libjpeg-dev \
    libpng-dev \
    librdmacm1 \
    libibverbs1 \
    ibverbs-providers \
    openssh-client \
    openssh-server \
    libsm6 \
    libxext6 \
    ffmpeg \
    libfontconfig1 \
    libxrender1 \
    libgl1-mesa-glx &&\
    apt-get clean && rm -rf /var/lib/apt/lists/*

# use user's conda env as base
ADD environment.yml /tmp/environment.yml
RUN conda env update -n base -f /tmp/environment.yml

# update pytorch installed from the above step to nightly
RUN conda update pytorch torchvision torchaudio -c pytorch-nightly -y

# install pytorch lightning nightly
RUN pip install https://github.com/PyTorchLightning/pytorch-lightning/archive/master.zip && \
    pip install jsonargparse[signatures] --upgrade

# (optional) update all conda pkgs
# RUN conda update --all
