lr: 0.001
weight_decay: 0.0005

net:
  class_path: src.models.components.simple_dense_net.SimpleDenseNet
  init_args:
    input_size: 784
    lin1_size: 256
    lin2_size: 256
    lin3_size: 256
    output_size: 10
