# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: ${oc.env:AMLT_OUTPUT_DIR}
  name: null
  version: ${name}
  log_graph: False
  default_hp_metric: True
  prefix: ""
