description: ML Template Experiment - MNIST

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: ml_template:latest # same as latest-azureml # see docker/Dockerfile_base_azureml
  setup:
    - pip install -e .

# $CONFIG_DIR is expanded to the directory of this config file.
code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data
  remote_dir: lightning_template/data

# some environment variables to ease up setting of jobs
env_defaults:
  NUM_NODES: 1
  NUM_GPUS: 1

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
# let's use the environment variables defined in "env_defaults" section above to make things a bit cleaner
# Two $ will be replaced with a single $ when loading the yaml.
# Variables with single $ will be replaced from your local environment before interpreting this yaml file.
jobs:
  - name: train_${NUM_NODES}xG${NUM_GPUS}
    sku: ${NUM_NODES}xG${NUM_GPUS}
    process_count_per_node: ${NUM_GPUS}
    submit_args:
      container_args:
        shm_size: 650g
      env:
        { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
        # {AZUREML_COMPUTE_USE_COMMON_RUNTIME: True, NCCL_DEBUG: INFO, NCCL_DEBUG_SUBSYS: ALL} # for debugging

    command:
      - export MKL_THREADING_LAYER="GNU"
      - python src/utils/system_monitor.py --watch_every_n_seconds 1 &
      - python src/train.py base=configs/train.yaml \
        trainer.num_nodes=${NUM_NODES} \
        trainer.gpus=${NUM_GPUS} \
        trainer.max_epochs=50
