# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: ML Template Experiment - MNIST

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: ml_template:latest
  setup:
    - pip install -e .

# $CONFIG_DIR is expanded to the directory of this config file.
code:
  local_dir: $CONFIG_DIR/../

data:
  local_dir: $CONFIG_DIR/../data
  remote_dir: lightning_template/data

# some environment variables to ease up setting of jobs
env_defaults:
  NUM_NODES: 2
  NUM_GPUS: 4

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
  # amlt run jobs/amlt.yaml --target-name V100-1x-ded :train_1_node_1_gpu ml-template-mnist
  - name: train_1_node_1_gpu
    sku: 1xG1
    submit_args:
      container_args:
        shm_size: 650g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
    command:
      - python src/train.py -c configs/train.yaml --trainer.gpus=1 --trainer.max_epochs=50

  # amlt run jobs/amlt.yaml --target-name V100-4x-ded :train_1_node_4_gpus ml-template-mnist
  - name: train_1_node_4_gpus
    sku: 1xG4
    process_count_per_node: 4
    submit_args:
      container_args:
        shm_size: 650g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
    command:
      - python src/train.py -c configs/train.yaml --trainer.gpus=4 --trainer.max_epochs=50

  # amlt run jobs/amlt.yaml --target-name V100-4x-ded :train_distributed_2_nodes_4_gpus ml-template-mnist
  - name: train_distributed_2_nodes_4_gpus
    sku: 2xG4
    process_count_per_node: 4
    submit_args:
      container_args:
        shm_size: 650g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
    command:
      - python src/train.py -c configs/train.yaml --trainer.num_nodes=2 --trainer.gpus=4 --trainer.max_epochs=50

  # let's use the environment variables defined in "env_defaults" section above to make things a bit cleaner
  # Two $ will be replaced with a single $ when loading the yaml.
  # Variables with single $ will be replaced from your local environment before interpreting this yaml file.

  # amlt run jobs/amlt.yaml --target-name V100-4x-ded :train_distributed_2_nodes_4_gpus_env_vars ml-template-mnist
  - name: train_distributed_2_nodes_4_gpus_env_vars
    sku: ${NUM_NODES}xG${NUM_GPUS}
    process_count_per_node: ${NUM_GPUS}
    submit_args:
      container_args:
        shm_size: 650g
      env:
        { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
        # {AZUREML_COMPUTE_USE_COMMON_RUNTIME: True, NCCL_DEBUG: INFO, NCCL_DEBUG_SUBSYS: ALL} # for debugging

    command:
      - python src/train.py -c configs/train.yaml --trainer.num_nodes=${NUM_NODES} --trainer.gpus=${NUM_GPUS} --trainer.max_epochs=50
