name: Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "docker/**"
      - "!dockers/README.md"
      - "requirements.txt"
      - "environment.yml"
      - ".github/workflows/*docker*.yml"
      - "setup.py"
      - "setup.cfg"

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        YEAR_MONTH: ["22.04"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            YEAR_MONTH=${{ matrix.YEAR_MONTH }}
          file: docker/Dockerfile
          push: false
        timeout-minutes: 50
